package syntax_analysis;

/* Generated By:JJTree: Do not edit this line. ASTMult.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMult extends SimpleNode {
  public ASTMult(int id) {
    super(id);
  }

  public ASTMult(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f6ed0b218ae7a040364a714281567d40 (do not edit this line) */
