package syntax_analysis;

/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTMULT = 3;
  public int JJTMYID = 4;
  public int JJTINTEGER = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Mult",
    "MyID",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=432665b59d6a9b61548f015c15f3f504 (do not edit this line) */
