package syntax_analysis;/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int INT = 7;
    /**
     * RegularExpression Id.
     */
    int IDENTIFIER = 8;
    /**
     * RegularExpression Id.
     */
    int CHAR = 9;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
            "<EOF>",
            "\" \"",
            "\"\\t\"",
            "\"\\n\"",
            "\"\\r\"",
            "<token of kind 5>",
            "<token of kind 6>",
            "<INT>",
            "<IDENTIFIER>",
            "<CHAR>",
            "\";\"",
            "\"+\"",
            "\"-\"",
            "\"*\"",
            "\"/\"",
            "\"%\"",
            "\"(\"",
            "\")\"",
    };

}
